name: CI

on:
  push:
    branches:
      - '*'
#  pull_request:
#    branches:
#      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Grab The Source Code
      - name: Checkout
        uses: actions/checkout@v2

      # Restore all of our .NET Core Local Tools
      - name: .NET Core Local Tool Restore
        run: dotnet tool restore --add-source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json

      # Verify that the code is formatted correctly
      - name: Format Files
        run: dotnet format --fix-style warn --fix-analyzers warn --check

      # Build the Project
      - name: Build Source
        run: dotnet build --configuration Release

      # Package the Project
      - name: Package
        run: dotnet pack --configuration Release --no-build --version-suffix "ci-${{ github.sha }}"

      # Upload the Asset
      - name: Upload Artifacts to GitHub
        uses: actions/upload-artifact@v2
        with:
            name: MsBuildDuplicateProjectGuid-${{ github.sha }}
            path: |
              nupkg/*.nupkg

      # Deploy the Package
      - name: Deploy to GitHub Packages
        if: ${{ github.ref == 'refs/heads/main' }}
        run: echo perform a deploy if on main!