name: CI

on:
  push:
    branches:
      - '*'
#  pull_request:
#    branches:
#      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Grab The Source Code
      - name: Checkout
        uses: actions/checkout@v2

      # Configure Dotnet to push packages to GitHub Package Repo (GPR)
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x' # SDK Version to use.
          source-url: https://nuget.pkg.github.com/${{github.repository_owner}}/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      # Restore all of our .NET Core Local Tools
      - name: .NET Core Local Tool Restore
        run: dotnet tool restore --add-source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json

      # Verify that the code is formatted correctly
      - name: Format Files
        run: dotnet format --fix-style warn --fix-analyzers warn --check

      # Build the Project
      - name: Build Source
        run: dotnet build --configuration Release

      # Package the Project
      - name: Package
        run: dotnet pack --configuration Release --no-build --version-suffix "ci-${{ github.sha }}"

      # Publish the Package
      - name: Publish the package to GPR
        run: dotnet nuget push nupkg/*.nupkg

      # Deploy the Package
      - name: Deploy to GitHub Packages
        if: ${{ github.ref == 'refs/heads/main' }}
        run: echo perform a deploy if on main!